KALDI_ROOT=/home/zhangjl/git/asr/eesen
EESEN_ROOT=/home/zhangjl/git/asr/eesen
SEGMENTS=show.s.seg

# 8k models from switchboard
#ACWT=0.6
#GRAPH_DIR?=$(EESEN_ROOT)/asr_egs/swbd/v1-pitch/data/lang_phn_sw1_fsh_tgpr
#MODEL_DIR?=$(EESEN_ROOT)/asr_egs/swbd/v1-pitch/exp/train_phn_l5_c320
#sample_rate=8k
#fbank=make_fbank_pitch

# 16k models from tedlium
#ACWT=0.7
#GRAPH_DIR?=$(EESEN_ROOT)/asr_egs/tedlium/v1/data/lang_phn_test
#GRAPH_DIR?=$(EESEN_ROOT)/asr_egs/tedlium/v1/data/lang_phn_test_newlm
#MODEL_DIR?=$(EESEN_ROOT)/asr_egs/tedlium/v1/exp/train_phn_l5_c320
#sample_rate=16k
#fbank=make_fbank

# td v3000
ACWT=0.7
# choose one GRAPH_DIR below
GRAPH_DIR?=/asrDataCenter/dataCenter/modelCenter/asr/tdReArrange/v6000_8k16bit/data/lang_phn_test
#GRAPH_DIR?=/asrDataCenter/dataCenter/modelCenter/asr/tdReArrange/v6000_8k16bit_segError/data/lang_phn_test
# most general, largest vocabulary/grammar
MODEL_DIR?=/asrDataCenter/dataCenter/modelCenter/asr/tdReArrange/v6000_8k16bit/exp/train_phn_l5_c320
sample_rate=8k
fbank=make_fbank
